# 🔄 Pipeline ETL
## Nettoyage et transformation

In [2]:
import sys
sys.path.append('..')
  
import pandas as pd
import glob
import os
from pipeline.cleaner import DataCleaner
from pipeline.transformer import DataTransformer
    
print("✅ Modules importés")

✅ Modules importés

In [3]:
# Charger le dernier fichier brut

csv_files = glob.glob('../data/raw/jobs_*.csv')
if csv_files:
    latest_file = max(csv_files, key=os.path.getctime)
    df_raw = pd.read_csv(latest_file)
    print(f"📁 Fichier chargé: {latest_file}")
    print(f"📊 Dimensions: {df_raw.shape}")
else:
    print("❌ Aucun fichier trouvé")

📁 Fichier chargé: ../data/raw\jobs_20260310_111857.csv
📊 Dimensions: (75, 10)

In [4]:
# Nettoyage

cleaner = DataCleaner()
df_clean = cleaner.clean(df_raw)
df_clean.head()

,url,titre,entreprise,date_publication,region,ville,contrat,experience,niveau_etude,competences_cles
0,https://www.emploi.ma/offre-emploi-maroc/achet...,Acheteur(se) / Spécialiste Achats Parapharmace...,OPENSNZ TECHNOLOGY,2026-03-10,Oujda,Oujda,CDI,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+3 - Bac+4 - Bac+5 et plus,Santé
1,https://www.emploi.ma/offre-emploi-maroc/assis...,Assistante Administrative en Intérim - Bouskoura,TECTRA CASA BOURGOGNE – RECRUTEMENT,2026-03-10,Casablanca-Mohammedia,Bouskoura,Intérim,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+2 - Bac+3 - Bac+4 - Bac+5 et plus,Assistanat - Gestion du Courrier - Secrétariat...
2,https://www.emploi.ma/offre-emploi-maroc/assis...,Assistante de Production,BOTTU,2026-03-10,Casablanca-Mohammedia,Non spécifié,CDI - Intérim,Expérience entre 2 ans et 5 ans,Bac+2,Classement des Documents - Secrétariat - Archi...
3,https://www.emploi.ma/offre-emploi-maroc/conse...,Conseiller(e) Pédagogique - Casablanca,CALLIOPE,2026-03-10,Casablanca-Mohammedia,Casablanca,CDI,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+3 - Bac+4 - Bac+5 et plus,Vente - Vente
4,https://www.emploi.ma/offre-emploi-maroc/comme...,Commercial Bois - Casablanca,SDK WOOD,2026-03-10,Casablanca-Mohammedia - Fès - Rabat-Salé-Kénitra,Casablanca,CDI,Expérience entre 2 ans et 5 ans,Bac+2 - Bac+3 - Bac+4 - Bac+5 et plus,Techniques de négociation - Gestion de la rela...

In [5]:
# Transformation

transformer = DataTransformer()
df_trans = transformer.transform(df_clean)
df_trans.head()

,url,titre,entreprise,date_publication,region,ville,contrat,experience,niveau_etude,competences_cles,skills_list,experience_cat,annee,mois
0,https://www.emploi.ma/offre-emploi-maroc/achet...,Acheteur(se) / Spécialiste Achats Parapharmace...,OPENSNZ TECHNOLOGY,2026-03-10,Oujda,Oujda,CDI,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+3 - Bac+4 - Bac+5 et plus,Santé,[Santé],Junior (2-5 ans),2026,3
1,https://www.emploi.ma/offre-emploi-maroc/assis...,Assistante Administrative en Intérim - Bouskoura,TECTRA CASA BOURGOGNE – RECRUTEMENT,2026-03-10,Casablanca-Mohammedia,Bouskoura,Intérim,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+2 - Bac+3 - Bac+4 - Bac+5 et plus,Assistanat - Gestion du Courrier - Secrétariat...,"[Assistanat, Gestion du Courrier, Secrétariat,...",Junior (2-5 ans),2026,3
2,https://www.emploi.ma/offre-emploi-maroc/assis...,Assistante de Production,BOTTU,2026-03-10,Casablanca-Mohammedia,Non spécifié,CDI - Intérim,Expérience entre 2 ans et 5 ans,Bac+2,Classement des Documents - Secrétariat - Archi...,"[Classement des Documents, Secrétariat, Archiv...",Junior (2-5 ans),2026,3
3,https://www.emploi.ma/offre-emploi-maroc/conse...,Conseiller(e) Pédagogique - Casablanca,CALLIOPE,2026-03-10,Casablanca-Mohammedia,Casablanca,CDI,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+3 - Bac+4 - Bac+5 et plus,Vente - Vente,"[Vente, Vente]",Junior (2-5 ans),2026,3
4,https://www.emploi.ma/offre-emploi-maroc/comme...,Commercial Bois - Casablanca,SDK WOOD,2026-03-10,Casablanca-Mohammedia - Fès - Rabat-Salé-Kénitra,Casablanca,CDI,Expérience entre 2 ans et 5 ans,Bac+2 - Bac+3 - Bac+4 - Bac+5 et plus,Techniques de négociation - Gestion de la rela...,"[Techniques de négociation, Gestion de la rela...",Junior (2-5 ans),2026,3

In [6]:
# Sauvegarde

df_trans.to_csv('../data/processed/jobs_clean.csv', index=False)
print(f"✅ Données sauvegardées dans data/processed/jobs_clean.csv")

✅ Données sauvegardées dans data/processed/jobs_clean.csv