# 🕷️ Scraper Emploi.ma
## Tests et validation

In [1]:
import sys
sys.path.append('..')

from scraper.scraper import EmploiMaScraper
from scraper.config import BASE_URL
import pandas as pd

print(f"✅ Scraper initialisé: {BASE_URL}")

✅ Scraper initialisé: https://www.emploi.ma

In [2]:
# Initialisation

scraper = EmploiMaScraper()

In [3]:
# Test sur une page

urls = scraper.get_page_urls(page_num=0)
print(f"🔍 {len(urls)} offres sur la page 1")

🔍 25 offres sur la page 1

In [4]:
# Test sur une offre

if urls:
    job = scraper.parse_job(urls[0])
    pd.DataFrame([job]).T

In [11]:
# Petit scraping (3 pages)

df_test = scraper.run(max_pages=3)
df_test.head()

,url,titre,entreprise,date_publication,region,ville,contrat,experience,niveau_etude,competences_cles
0,https://www.emploi.ma/offre-emploi-maroc/achet...,Acheteur(se) / Spécialiste Achats Parapharmace...,OPENSNZ TECHNOLOGY,10.03.2026,Oujda,Oujda,CDI,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+3 - Bac+4 - Bac+5 et plus,Santé
1,https://www.emploi.ma/offre-emploi-maroc/assis...,Assistante Administrative en Intérim - Bouskoura,TECTRA CASA BOURGOGNE – RECRUTEMENT,10.03.2026,Casablanca-Mohammedia,Bouskoura,Intérim,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+2 - Bac+3 - Bac+4 - Bac+5 et plus,Assistanat - Gestion du Courrier - Secrétariat...
2,https://www.emploi.ma/offre-emploi-maroc/assis...,Assistante de Production,BOTTU,10.03.2026,Casablanca-Mohammedia,None,CDI - Intérim,Expérience entre 2 ans et 5 ans,Bac+2,Classement des Documents - Secrétariat - Archi...
3,https://www.emploi.ma/offre-emploi-maroc/conse...,Conseiller(e) Pédagogique - Casablanca,CALLIOPE,10.03.2026,Casablanca-Mohammedia,Casablanca,CDI,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+3 - Bac+4 - Bac+5 et plus,Vente - Vente
4,https://www.emploi.ma/offre-emploi-maroc/comme...,Commercial Bois - Casablanca,SDK WOOD,10.03.2026,Casablanca-Mohammedia - Fès - Rabat-Salé-Kénitra,Casablanca,CDI,Expérience entre 2 ans et 5 ans,Bac+2 - Bac+3 - Bac+4 - Bac+5 et plus,Techniques de négociation - Gestion de la rela...

In [5]:
# Petit scraping (30 pages)

df_test = scraper.run(max_pages=30)
df_test.head()

,url,titre,entreprise,date_publication,region,ville,contrat,experience,niveau_etude,competences_cles
0,https://www.emploi.ma/offre-emploi-maroc/pilot...,Pilote Qualité - Tanger,TESCA MOROCCO,04.03.2026,Tanger-Tétouan-Al Hoceïma,Tanger,CDI,Expérience entre 2 ans et 5 ans,Bac+5 et plus,Qualité - Maintenance - Production - Managemen...
1,https://www.emploi.ma/offre-emploi-maroc/respo...,Responsable Maintenance - Casablanca,BOTTU,12.02.2026,Casablanca-Mohammedia,Casablanca,CDI,Expérience entre 5 ans et 10 ans,Bac+5 et plus,Maintenance - Production - Électromécanique - ...
2,https://www.emploi.ma/offre-emploi-maroc/chef-...,Chef d’Équipe – Installation Photovoltaïque - ...,TECTRA CASA TERTIAIRE – RECRUTEMENT,10.03.2026,Casablanca-Mohammedia,Casablanca,CDI - Intérim,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+2 - Bac+3,Production - Qualité - Maintenance - Montage -...
3,https://www.emploi.ma/offre-emploi-maroc/assis...,Assistant(e) Marketing et Communication - Bous...,SEPALUMIC,24.02.2026,Casablanca-Mohammedia,Bouskoura,CDI,Expérience entre 2 ans et 5 ans,Bac+3,Communication Marketing - Marketing Digital - ...
4,https://www.emploi.ma/offre-emploi-maroc/assis...,Assistante de Direction - Casablanca,GROUPE MCE,24.02.2026,Casablanca-Mohammedia,Casablanca,CDI,Expérience entre 2 ans et 5 ans - Expérience e...,Bac+2 - Bac+3 - Bac+4 - Bac+5 et plus,Assistanat - Support - POWERPOINT - Administra...